// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Data;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241216104640_SeedHotelTabLeWithUpdatedDate")]
    partial class SeedHotelTabLeWithUpdatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication4.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rooms")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3200),
                            Details = "Hotels in Goa Book Now, Hotels in Goa! Don't Miss Today's Best Deals",
                            ImageUrl = "https://hotels.razola.xyz/i/g-b790c4f3d4e705af6e7d4b7801e217fe0a0ed75fd4451861442ded35692135af.jpeg?z=1589047845#s1500x1000",
                            Name = "diamond",
                            Rate = 43245.0,
                            UpdatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3210),
                            password = "fhj123",
                            rooms = 4
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3212),
                            Details = "Hotels in Goa Book Now, Hotels in Goa! Don't Miss Today's Best Deals",
                            ImageUrl = "https://q-xx.bstatic.com/xdata/images/hotel/max1200/138405161.jpg?k=e447b65d28d229f95cb41ee219d36d8588548fe8bbb7f6495af2441c086ecea6&o=",
                            Name = "GOLD",
                            Rate = 33245.0,
                            UpdatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3212),
                            password = "JHG123",
                            rooms = 4
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3214),
                            Details = "Hotels in Goa Book Now, Hotels in Goa! Don't Miss Today's Best Deals",
                            ImageUrl = "https://r1imghtlak.mmtcdn.com/971eaf269e7f11eb98f10242ac110002.jpg",
                            Name = "SILVER",
                            Rate = 23245.0,
                            UpdatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3214),
                            password = "POI123",
                            rooms = 4
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3216),
                            Details = "Hotels in Goa Book Now, Hotels in Goa! Don't Miss Today's Best Deals",
                            ImageUrl = "https://tse2.mm.bing.net/th?id=OIP.HSxTr3mBPKE7vGRHlvZhCQHaE8&pid=Api&P=0&h=180",
                            Name = "CLASSIC",
                            Rate = 13245.0,
                            UpdatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3217),
                            password = "FDS123",
                            rooms = 4
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3219),
                            Details = "Hotels in Goa Book Now, Hotels in Goa! Don't Miss Today's Best Deals",
                            ImageUrl = "http://pix6.agoda.net/hotelImages/148/148753/148753_15091018110035867258.jpg?s=1100x825",
                            Name = "BASIC",
                            Rate = 10000.0,
                            UpdatedDate = new DateTime(2024, 12, 16, 16, 16, 39, 614, DateTimeKind.Local).AddTicks(3219),
                            password = "SDR123",
                            rooms = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
